### PR TITLE
simplify routes in main.go

### PR DESCRIPTION
**Pull request by santiaago**
Created 3 func 'alias'
checkErrors, authorized, adminAuthorized

It is easier to read now.

### CODE REVIEW

**Comment by santiaago** [comment]
@rjourde what do you think of this?

**Comment by rjourde** [comment]
nice but I would put these alias functions in a helper and not directly in main.go

**Comment by santiaago** [comment]
They are only used in main.go that is the point. to get rid of the `helpers.`

**Comment by rjourde** [comment]
Ok you can merge the PR

**Comment by santiaago** [comment]
goapp deployed

**Pull request merged**
