### PR TITLE
Issue 588

### PR DESCRIPTION
**Pull request by santiaago**
#588 

Improve Predictions performance.

`j/tournaments/:tournamentId/:teamId/calendarwithprediction?groupby=`

takes **7 seconds**

### CODE REVIEW

**Comment by santiaago** [comment]
List of user teams and memcache will be done in different issues.

**Comment by rjourde** [comment]
deployed.

**Comment by santiaago** [comment]
I did some measurements on the times taken in **production**:

It now takes less than2 seconds consistently :+1: 
screen shot 2015-06-18 at 23 38 17

**Comment by rjourde** [comment]
Nice. Avec du memcache ça serait encore mieux

**Pull request merged**
