### PR TITLE
Review Gonawin style

### PR DESCRIPTION
**Pull request by rjourde**
- need to buy high resolution background image
- deleted signin page
- had to review activities page
#559

### CODE REVIEW

**Comment by rjourde** [comment]
Still work in progress

**Comment by rjourde** [comment]
Could review this PR. So I could create a new one for Champions League tournament

**Comment by santiaago** [comment]
Looks great except for the `controllers/users/users.go` remark. :+1:

**Comment by rjourde** [comment]
Ok cool. I will do change you are requesting and buy the picture!

**Comment by santiaago** [comment]
cool awesome.

**Comment by rjourde** [comment]
let me know what do you thing. I remove the bidulio at the top because too deguelasse if we try to set transparent background.

**Comment by rjourde** [comment]
I will merge the pull request in order to push the champions league. If there is something you don't like on the home page, we will change it after.

**Comment by santiaago** [comment]
looks good, thanks!

**Pull request merged**
