### PR TITLE
update to boostrap v3.3.2 and to angular 1.3.14

### PR DESCRIPTION
**Pull request by rjourde**
#543

### CODE REVIEW

**Comment by rjourde** [comment]
added update to angular 1.3.14 issue in the same pull request by mistake. So reopen it.

**Comment by rjourde** [comment]
Are you ok with the latest commit ? Can I merge the pull request ?

**Comment by rjourde** [comment]
let me know if it looks good and I will merge the pull request :)

**Comment by santiaago** [comment]
looks good

**Pull request merged**
