### PR TITLE
private team cannot be joined without consent #664

### PR DESCRIPTION
**Pull request by rjourde**

### CODE REVIEW

**Comment by santiaago** [comment]
should we also control this in the server side ?

**Comment by rjourde** [comment]
It is checked on the server side

**Comment by santiaago** [comment]
so why did it not worked :)

**Comment by rjourde** [comment]
It is the prupose of the PR. Did you look at the change ;)

**Comment by santiaago** [comment]
oh! sorry, I though this was on the front end side, great! :+1:

**Pull request merged**
