### PR TITLE
simplify controllers

### PR DESCRIPTION
**Pull request by santiaago**
There are different things we can do to simplify the controllers.
This PR is to address this.

Some things that I have seen:
 
 * check HTTP request first and exit if not supported. This removes an indentation from the code.
 * create some functions so that it is easy to read the controller and understand what is happening.

The idea is to merge this to `master` when the **CL** finishes.

### CODE REVIEW

**Comment by rjourde** [comment]
nice but what is the meaning of "at" in "at addAdmin" ?

**Comment by santiaago** [comment]
oops, it should be `aa`

**Comment by rjourde** [comment]
Ok merge

**Comment by santiaago** [comment]
I don't want to merge this PR until the CL is done.

**Comment by rjourde** [comment]
Ok

**Pull request merged**
