### PR TITLE
Issue 662 do not publish activity if user does not get points

### PR DESCRIPTION
**Pull request by santiaago**

### CODE REVIEW

**Comment by rjourde** [comment]
activities are no longer published even when I get some points

**Comment by santiaago** [comment]
I re tested and I am not able to reproduce this. Could you please test again?

**Comment by rjourde** [comment]
I still have the issue.
Try:
1. Win 3 points -> activity OK
2. no points -> no activity
3. Win 1 point (tied match) -> no activity => bug
4. Win 3 points -> no activity => bug

image

**Comment by santiaago** [comment]
ok, one last question, are you sure you are predicting and settings scores in the same tournament

**Comment by rjourde** [comment]
Yes.

**Comment by santiaago** [comment]
I re tested and all works.
It does not make sense that your prediction happens after the game. 
They should be shown **before** the game.
All your predictions are after the result of the game...
screen shot 2015-06-25 at 21 57 01

**Comment by rjourde** [comment]
Ok you can merge

**Comment by santiaago** [comment]
could you please try to reproduce the issue and paste the logs here?

Thanks.

**Comment by rjourde** [comment]
Re-tested this morning and score activities were published properly. So I guess we can merge

**Comment by santiaago** [comment]
:+1:

**Pull request merged**
